services:
  api:
    build: .
    ports:
      - "8090:8000"
    env_file: .env
  
  web:
    image: caddy:alpine
    ports:
      - "8091:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sightseeing_app/build/web/:/usr/share/caddy